apiVersion: v1alpha1
kind: Role
metadata:
  name: syncpostai-role-ai-article-push-anonymous
  labels:
    halo.run/role-template: "true"
    halo.run/hidden: "true"
    rbac.authorization.halo.run/aggregate-to-anonymous: "true"
  annotations:
    rbac.authorization.halo.run/module: "智稿同步"
    rbac.authorization.halo.run/display-name: "推送 AI 文章"
rules:
  - apiGroups: ["api.syncpostai.sora.run"]
    resources: ["articles"]
    verbs: ["create"]
